# Generated by Django 3.2.6 on 2021-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplaces', '0002_auto_20210803_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ECCCAssignedProjectIdentfer',
            field=models.CharField(max_length=50, verbose_name='Proj. Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectTitleEnglish',
            field=models.CharField(max_length=250, verbose_name='Title (En)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectTitleFrench',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title (Fr)'),
        ),
        migrations.RemoveField(
            model_name='projectlocation',
            name='Project',
        ),
        migrations.AddField(
            model_name='projectlocation',
            name='Project',
            field=models.ManyToManyField(blank=True, null=True, to='pplaces.Project'),
        ),
    ]
