# Generated by Django 3.2.6 on 2021-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pplaces', '0003_auto_20210806_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlocation',
            name='Project',
        ),
        migrations.AddField(
            model_name='project',
            name='ProjectLocation',
            field=models.ManyToManyField(blank=True, null=True, to='pplaces.ProjectLocation'),
        ),
    ]
